const ui={snapshot:null,catalog:null,page:'overview',stageId:null,command:null,eventSource:null};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleCase=v=>String(v??'unknown').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const compact=v=>{if(v===null||v===undefined)return'—';if(typeof v==='boolean')return v?'YES':'NO';if(typeof v==='number')return new Intl.NumberFormat('en-US',{maximumFractionDigits:3}).format(v);return String(v)};
const shortHash=v=>v?`${String(v).slice(0,12)}…`:'—';
const STATUS={AVAILABLE:'good',CERTIFIED:'good',VALID:'good',SUPPORTED:'good',SINGLE_SESSION_PROSPECTIVE_MECHANISM_SUPPORTED:'good',CONSTRUCTED_NO_RUNTIME_RECORDS:'info',NO_DURABLE_RUNTIME_RECORDS:'muted',DATA_BLOCKED:'warn',BLOCKED:'warn',UNAVAILABLE:'muted',SERVER_READ_ONLY:'muted',READ_ONLY:'info',NOT_EARNED:'bad',INVALID:'bad',LOCKED:'bad',LOCKED_FALSE:'bad',NONE:'bad',SHADOW_ONLY:'info',AVAILABLE_MUTATION:'warn',NOT_CONSTRUCTED:'muted'};
function statusClass(v){return STATUS[String(v??'').toUpperCase()]||'muted'}
function badge(v,override){return `<span class="badge ${override||statusClass(v)}">${esc(titleCase(v))}</span>`}
function panel(title,body,actions=''){return `<section class="panel"><div class="panel-head"><div><div class="eyebrow">SYSTEM SURFACE</div><h2>${esc(title)}</h2></div>${actions}</div>${body}</section>`}
function jsonBlock(v){return `<pre class="json-tree">${esc(JSON.stringify(v??{},null,2))}</pre>`}
function metricCard(label,value,sub='',accent='cyan'){return `<article class="metric-card"><div class="metric-head"><span>${esc(label)}</span><span class="metric-accent ${accent}"></span></div><div class="metric-value">${esc(compact(value))}</div><div class="metric-sub">${sub}</div></article>`}
function kvGrid(items){return `<div class="kv-grid">${Object.entries(items).map(([k,v])=>`<div class="kv"><span>${esc(titleCase(k))}</span><strong>${esc(compact(v))}</strong></div>`).join('')}</div>`}
function truthItem(icon,title,text){return `<div class="truth-item"><div class="truth-icon">${icon}</div><div><strong>${esc(title)}</strong><p>${esc(text)}</p></div></div>`}
function getStage(id){return(ui.snapshot?.stages||[]).find(s=>s.id===id)}
function monitorSection(name){return ui.snapshot?.monitor?.sections?.[name]||{}}
function sectionData(name){const v=monitorSection(name)?.data;return v&&typeof v==='object'?v:{}}
const NAV=[
 {group:'System',items:[['overview','Overview','⌂']]},
 {group:'Perception',items:[['stage:Z1','Observations · Z1','◉'],['stage:Z2','Representations · Z2','◇'],['stage:Z9','Market Context · Z9','◎']]},
 {group:'Intelligence',items:[['stage:Z3','Predictions · Z3','↗'],['stage:Z4','Models · Z4','⬡'],['stage:Z5','Lifecycle · Z5','⟳'],['stage:Z8','Assembly · Z8','✣'],['intelligence','Intelligence · Z10','✦']]},
 {group:'Evaluation',items:[['stage:Z6','Outcomes · Z6','⊙'],['stage:Z7','Competence · Z7','◈']]},
 {group:'Governance',items:[['certification','Certification','✓'],['lineage','Evidence & Lineage','⌘']]},
 {group:'Operations',items:[['controls','Control Center','⚙'],['development','Development','</>']]},
 {group:'Institution',items:[['benjamin','Benjamin Bridge','B']]}
];
function renderNav(){$('#nav').innerHTML=NAV.map(g=>`<div class="nav-group"><div class="nav-label">${esc(g.group)}</div>${g.items.map(([id,label,icon])=>{const selected=(id.startsWith('stage:')&&ui.page==='stage'&&ui.stageId===id.split(':')[1])||ui.page===id;return `<button class="nav-item ${selected?'active':''}" data-view="${esc(id)}"><span class="nav-icon">${esc(icon)}</span><span>${esc(label)}</span></button>`}).join('')}</div>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)))}
function openView(v){if(v.startsWith('stage:')){ui.page='stage';ui.stageId=v.split(':')[1]}else{ui.page=v;ui.stageId=null}renderNav();render()}
function pipelineNode(stage){const entries=Object.entries(stage.metrics||{}).filter(([,v])=>typeof v==='number');const tiny=entries.length?entries.slice(0,1).map(([k,v])=>`${compact(v)} ${titleCase(k)}`).join(''):titleCase(stage.availability);return `<button class="pipeline-node ${statusClass(stage.availability)}" data-stage="${esc(stage.id)}"><span class="stage-id">${esc(stage.id)}</span><strong>${esc(stage.name)}</strong><small>${esc(tiny)}</small>${badge(stage.availability)}</button>`}
function pipeline(){const stages=ui.snapshot?.stages||[],order=['Z1','Z2','Z3','Z4','Z5','Z6','Z7','Z8','Z9'];return `<div class="pipeline-wrap"><div class="pipeline">${order.map((id,i)=>{const s=stages.find(x=>x.id===id);return s?`${pipelineNode(s)}${i<order.length-1?'<div class="lineage-arrow">→</div>':''}`:''}).join('')}<div class="lineage-arrow">→</div><div class="pipeline-node future"><span class="stage-id">Z10</span><strong>Intelligence</strong><small>Not constructed yet</small>${badge('UNAVAILABLE')}</div></div></div>`}
function operatorMode(){return ui.catalog?.mutations_enabled?badge('AVAILABLE_MUTATION','warn'):badge('READ_ONLY','info')}
function certCard(title,status,id,hash,description){return `<article class="cert-card"><div class="stage-top"><div><span class="eyebrow">CERTIFICATION</span><h3>${esc(title)}</h3></div>${badge(status)}</div><p>${esc(description)}</p><div class="micro-metric"><span>Evidence</span><b>${esc(id||'—')}</b></div><div class="micro-metric"><span>Hash</span><code>${esc(shortHash(hash))}</code></div></article>`}
function qualityView(data){const keys=['repository_validation','evidence_integrity_check','timestamp_violations','open_incidents'];return `<div class="quality-matrix">${keys.map(k=>{let v=data?.[k];if(Array.isArray(v))v=v.length;return `<div class="qcell"><span>${esc(titleCase(k))}</span><strong>${esc(compact(v))}</strong></div>`}).join('')}<div class="qcell"><span>UI principle</span><strong>NO FABRICATED HEALTH %</strong></div></div>`}
function overview(){const s=ui.snapshot||{},cert=s.certification||{},z1=getStage('Z1'),z2=getStage('Z2'),z3=getStage('Z3'),z9=getStage('Z9'),dq=sectionData('data_quality');const health=sectionData('system_health'),validation=health.validation_status||health.repository_validation||'unknown';return `<div class="page-stack fade-in">
<section class="hero"><div class="hero-grid"><div><div class="hero-kicker">ZLJ / PERCEPTION → EVIDENCE → INTELLIGENCE</div><h2>See the market. Prove what was seen. Learn whom to trust.</h2><p>Z1–Z9 converts raw provider evidence into point-in-time market state, falsifiable forecasts, measured competence, adaptive belief, and broader market context for Benjamin—without giving ZLJ capital or execution authority.</p><div class="flow-band"><span>MARKET</span><b>→</b><span>ZLJ SEES</span><b>→</b><span>BENJAMIN DECIDES</span><b>→</b><span>WATCHMAN GOVERNS</span><b>→</b><span>HAND EXECUTES</span></div></div><aside class="hero-aside"><div class="hero-stat"><span>System mode</span><strong>SHADOW ONLY</strong></div><div class="hero-stat"><span>Operator mode</span>${operatorMode()}</div><div class="hero-stat"><span>Capital authority</span><strong>NONE</strong></div><div class="hero-stat"><span>Live execution</span><strong class="locked-text">LOCKED</strong></div></aside></div></section>
<div class="grid grid-4">${metricCard('Canonical Z1 batches',z1?.metrics?.canonical_batches??0,'Derived from immutable provider evidence')}${metricCard('Z2 representation frames',z2?.metrics?.representation_frames??0,'Point-in-time instrument state','blue')}${metricCard('Durable Z3 predictions',z3?.metrics?.prediction_entries??0,'Falsifiable claims, not trade instructions','violet')}${metricCard('Z9 context frames',z9?.metrics?.context_frames??0,'Market-wide context available to assembly','green')}</div>
${panel('Z1–Z9 Intelligence Flow',pipeline(),'<span class="panel-actions">Every stage is inspectable</span>')}
<div class="grid grid-2">${panel('Truth & Data Quality',`<div class="truth-list">${truthItem('⏱','Point-in-time safe','Z2/Z9 reject future-known evidence rather than quietly filtering it.')}${truthItem('⌘','Provenance bound','Stage artifacts bind exact source IDs and hashes so lineage is reconstructable.')}${truthItem('◇','Unknown stays unknown','Missing context is UNAVAILABLE or DATA_BLOCKED; the UI does not invent a neutral value.')}${truthItem('↺','Replayable','Frozen Z8 evidence is rerun in CI to prove later work did not rewrite the past.')}</div><div class="info-banner">Repository validation: <b>${esc(compact(validation))}</b> · Operator journal: <b>${esc(s.system?.operator_journal||'UNKNOWN')}</b></div>`)}${panel('What Benjamin Gains',`<div class="truth-list">${truthItem('1','Traceable facts','Z1 ensures source quality and canonical identity before intelligence begins.')}${truthItem('2','Market state','Z2 turns noisy feeds into point-in-time representations.')}${truthItem('8','Measured belief','Z7/Z8 weight specialists by evidence instead of prestige or static rules.')}${truthItem('9','Situational awareness','Z9 adds liquidity, volatility, correlation and spot/derivative context.')}</div>`)}</div>
<div class="cert-grid">${certCard('Z8 historical real-data',cert.z8_historical?.decision,cert.z8_historical?.experiment_id,cert.z8_historical?.result_hash,'Adaptive weighting changed its beliefs but did not beat equal weighting on the frozen first historical window.')}${certCard('Z8 prospective mechanism',cert.z8_prospective?.decision,cert.z8_prospective?.experiment_id,cert.z8_prospective?.result_hash,'The Z1→Z8 chain operated prospectively without future knowledge or capital.')}${certCard('Z9 construction',cert.z9?.construction,'Market context layer',null,'Construction is certified; empirical market-wide/contextual performance claims remain data-gated.')}</div>${panel('Data Quality Snapshot',qualityView(dq))}</div>`}
const STAGE_INPUTS={Z1:'Raw provider evidence, stream manifests, provider metadata',Z2:'Qualified Z1 canonical observations',Z3:'Exact Z2 representation frame + model output',Z4:'Model definition, parameters, target/horizon contract',Z5:'Z4 identity + qualification evidence',Z6:'Z3 prediction + later qualified Z2 frame',Z7:'Durable Z3 predictions + Z6 outcomes',Z8:'Same-frame specialist predictions + Z5 eligibility + prior Z7 competence',Z9:'All durable Z2 history knowable at cutoff T + governed ModelContextProfiles'};
const STAGE_OUTPUTS={Z1:'CanonicalObservation batches',Z2:'RepresentationFrame',Z3:'Prediction journal entries',Z4:'Immutable ModelDefinition candidates',Z5:'Lifecycle transition journal + eligibility state',Z6:'PredictionOutcome',Z7:'CompetenceProfile reconstructed as-of cutoff',Z8:'Assembled Prediction + AssemblyReceipt',Z9:'MarketContextFrame + contextual assembly evidence'};
const STAGE_QUALITY={Z1:'Sequence integrity, freshness, completeness, provider provenance',Z2:'No-lookahead cutoff, source quality, venue separation',Z3:'Forward-evaluable vs research-only separation, immutable prediction lineage',Z4:'Immutable versioned identity and explicit supported horizons/targets',Z5:'Legal lifecycle transitions, evidence-kind gates, quarantine/supersession',Z6:'Fixed resolution lag, earliest qualified truth frame, deterministic retries',Z7:'Evidence-class separation, calibration, MAE/RMSE/Brier/sample strength',Z8:'Bounded weights, prior-only competence, durable components, anti-self-evaluation',Z9:'Point-in-time source selection, feature availability, context-profile causal authority'};
function stageControls(id){const map={Z5:['ACTIVATE_CONTEXT_PROFILE'],Z8:['RUN_QUALIFICATION'],Z9:['MATERIALIZE_CONTEXT','ACTIVATE_CONTEXT_PROFILE']},ids=map[id]||[],commands=(ui.catalog?.commands||[]).filter(c=>ids.includes(c.command_id));return commands.length?commands.map(controlCard).join(''):`<div class="empty-state"><strong>No direct mutation surface in v1.</strong><p>This stage remains inspectable; controls appear only when a governed backend operation exists.</p></div>`}
function stageLineage(active){const seq=['Z1','Z2','Z3','Z4','Z5','Z6','Z7','Z8','Z9'];return `<div class="lineage">${seq.map((id,i)=>`<div class="lineage-node ${id===active?'active':''}"><span>${id}</span><b>${esc(getStage(id)?.name||id)}</b></div>${i<seq.length-1?'<div class="lineage-arrow">→</div>':''}`).join('')}</div>`}
function stageCertification(id){const c=ui.snapshot?.certification||{};if(id==='Z8')return panel('Z8 Certification Truth',`<div class="cert-grid">${certCard('Historical performance',c.z8_historical?.decision,c.z8_historical?.experiment_id,c.z8_historical?.result_hash,'Frozen result. Later improvements cannot upgrade this experiment.')}${certCard('Prospective mechanism',c.z8_prospective?.decision,c.z8_prospective?.experiment_id,c.z8_prospective?.result_hash,'Single-session prospective support; not an economic superiority claim.')}${certCard('Broad / walk-forward','DATA_BLOCKED','Certification policy',null,'Insufficient independent qualified windows; scoring is intentionally blocked.')}</div>`);if(id==='Z9')return panel('Z9 Certification Truth',`<div class="cert-grid">${certCard('Construction',c.z9?.construction,'Z9 construction boundary',null,'Typed context, materializer, policy registry and causal lineage are constructed.')}${certCard('Market-wide empirical',c.z9?.market_wide_empirical,'Z9 policy',null,'Requires independent qualified multi-instrument contexts.')}${certCard('Contextual performance',c.z9?.contextual_performance,'Z8+Z9 policy',null,'Cannot be claimed until broad Z8 and market-wide Z9 prerequisites are met.')}</div>`);return''}
function stagePage(stage){if(!stage)return'<div class="empty-state">Unknown stage.</div>';return `<div class="page-stack fade-in"><section class="stage-hero"><div class="stage-orb"><div class="center">${esc(stage.id)}</div></div><div class="stage-copy"><div class="eyebrow">${esc(stage.group)} / ${esc(stage.id)}</div><h2>${esc(stage.name)}</h2><p>${esc(stage.purpose)}</p></div><div class="stage-detail">${badge(stage.availability)}<small>Authoritative source</small><code>${esc(stage.source)}</code></div></section><div class="stage-card-grid"><article class="stage-card"><span>INPUTS</span><p>${esc(STAGE_INPUTS[stage.id])}</p></article><article class="stage-card"><span>OUTPUTS</span><p>${esc(STAGE_OUTPUTS[stage.id])}</p></article><article class="stage-card"><span>QUALITY CONTRACT</span><p>${esc(STAGE_QUALITY[stage.id])}</p></article><article class="stage-card"><span>BENJAMIN BENEFIT</span><p>${esc(stage.benefit)}</p></article></div><div class="grid grid-2">${panel('Durable State',`${kvGrid(stage.metrics||{})}${jsonBlock(stage.metrics||{})}`)}${panel('Operator Controls',`<div class="control-grid">${stageControls(stage.id)}</div>`)}</div>${panel('Lineage Position',stageLineage(stage.id))}${stageCertification(stage.id)}</div>`}
function controlCard(command){const disabled=command.state!=='AVAILABLE'||(command.control_class==='MUTATING'&&!ui.catalog?.mutations_enabled),state=command.state==='AVAILABLE'&&command.control_class==='MUTATING'&&!ui.catalog?.mutations_enabled?'SERVER_READ_ONLY':command.state;return `<article class="control-card ${esc(command.state.toLowerCase())}"><div class="control-domain">${esc(command.control_class)}</div><div class="stage-top"><h3>${esc(command.label)}</h3>${badge(state)}</div><p>${esc(command.description)}</p><div class="control-benefit"><span>Benefit</span>${esc(command.benefit)}</div><button class="button ${command.control_class==='CONSTITUTIONALLY_LOCKED'?'ghost':'primary'}" data-command="${esc(command.command_id)}" ${disabled?'disabled':''}>${command.state==='LOCKED'?'Constitutionally locked':command.state==='UNAVAILABLE'?'Not implemented':command.control_class==='MUTATING'&&!ui.catalog?.mutations_enabled?'Operator mode required':'Open command'}</button></article>`}
function controlsPage(){const cmds=ui.catalog?.commands||[],domains=[...new Set(cmds.map(c=>c.domain))];return `<div class="page-stack fade-in"><section class="hero"><div class="hero-grid"><div><div class="hero-kicker">OPERATOR CONTROL PLANE</div><h2>Control through contracts, not direct state mutation.</h2><p>The browser can request only commands exposed by the authoritative operator catalog. A button does not create authority. Mutating commands require server-side operator mode, explicit confirmation, domain validation, idempotency, and durable receipts.</p></div><aside class="hero-aside"><div class="hero-stat"><span>Mutation gate</span>${operatorMode()}</div><div class="hero-stat"><span>Journal</span><strong>${esc(ui.snapshot?.system?.operator_journal||'UNKNOWN')}</strong></div><div class="hero-stat"><span>Execution authority</span><strong class="locked-text">NONE</strong></div></aside></div></section>${domains.map(d=>panel(titleCase(d),`<div class="control-grid">${cmds.filter(c=>c.domain===d).map(controlCard).join('')}</div>`)).join('')}${panel('Authority Boundary',`<div class="truth-list">${truthItem('UI','Browser','Requests operations; never writes domain state directly.')}${truthItem('API','FastAPI','Forwards a typed operator request to the kernel CLI.')}${truthItem('K','Kernel','Validates authority, state and causality, then calls the real domain operation.')}${truthItem('R','Receipt','Mutating operations are idempotent and hash-chain receipted; capital/execution effects remain NONE.')}</div>`)}</div>`}
function certificationPage(){const c=ui.snapshot?.certification||{};return `<div class="page-stack fade-in"><section class="hero"><div><div class="hero-kicker">EVIDENCE BEFORE CLAIMS</div><h2>Certification is a claim ceiling, not a marketing badge.</h2><p>Construction, historical support, prospective support, walk-forward evidence, and contextual performance are separate. A failed or data-blocked result remains visible.</p></div></section><div class="cert-grid">${certCard('Z8 first historical test',c.z8_historical?.decision,c.z8_historical?.experiment_id,c.z8_historical?.result_hash,'The adaptive mechanism operated, but equal weighting was marginally better on the frozen window.')}${certCard('Z8 prospective session',c.z8_prospective?.decision,c.z8_prospective?.experiment_id,c.z8_prospective?.result_hash,'Forward-evaluable mechanism support without capital or live execution.')}${certCard('Z9 construction',c.z9?.construction,'freeze/z9-construction-certified-20260903',null,'Market-wide/contextual machinery is constructed and dual-runtime qualified.')}${certCard('Z9 market-wide empirical',c.z9?.market_wide_empirical,'Z9-CERTIFICATION-POLICY-V1',null,'Data minimum not yet satisfied.')}${certCard('Z9 spot/derivative empirical',c.z9?.spot_derivative_empirical,'Z9-CERTIFICATION-POLICY-V1',null,'No derivatives claim is invented when derivatives data is unavailable.')}${certCard('Z8+Z9 contextual performance',c.z9?.contextual_performance,'Future walk-forward campaign',null,'Must outperform or tie base Z8 under preregistered contextual folds.')}</div>${panel('Frozen Evidence Inventory',jsonBlock(c.z8_inventory||{}))}</div>`}
function lineagePage(){const ev=sectionData('evidence_events'),dq=sectionData('data_quality');return `<div class="page-stack fade-in"><section class="hero"><div><div class="hero-kicker">TRACE ANY BELIEF BACKWARD</div><h2>Evidence should be explorable from intelligence to raw market facts.</h2><p>The UI treats lineage as a navigable graph: each derived object should disclose what it depended on, when it became knowable, and which immutable hashes bind the chain.</p></div></section>${panel('Canonical Causal Chain',`<div class="lineage"><div class="lineage-node"><span>Z1</span><b>Observation</b></div><div class="lineage-arrow">→</div><div class="lineage-node"><span>Z2</span><b>State</b></div><div class="lineage-arrow">→</div><div class="lineage-node"><span>Z3</span><b>Prediction</b></div><div class="lineage-arrow">→</div><div class="lineage-node"><span>Z6</span><b>Outcome</b></div><div class="lineage-arrow">→</div><div class="lineage-node"><span>Z7</span><b>Competence</b></div><div class="lineage-arrow">→</div><div class="lineage-node"><span>Z8</span><b>Assembly</b></div><div class="lineage-arrow">→</div><div class="lineage-node"><span>Z9</span><b>Context</b></div></div>`)}<div class="grid grid-2">${panel('Evidence Events',jsonBlock(ev))}${panel('Data Quality / Integrity',jsonBlock(dq))}</div>${panel('Proof Properties',`<div class="truth-list">${truthItem('#','Hash bound','Derived artifacts carry content hashes and exact source references.')}${truthItem('T','Time safe','Knowability cutoffs prevent future state from entering earlier reasoning.')}${truthItem('J','Journaled','Predictions, outcomes, model transitions, assemblies and operator mutations are append-only evidence.')}${truthItem('F','Frozen','Important empirical findings are preserved under dedicated freeze refs and regression gates.')}</div>`)}</div>`}
function developmentPage(){const cmd=(ui.catalog?.commands||[]).find(c=>c.command_id==='CODE_CHANGE');return `<div class="page-stack fade-in"><section class="hero"><div><div class="hero-kicker">FUTURE DEVELOPMENT SURFACE</div><h2>The console can become where you govern the code—without turning the browser into production.</h2><p>Source control will remain Git-backed. The intended workflow is proposal-first and qualification-first, so every change has a diff, branch, tests, evidence, and promotion boundary.</p></div></section>${panel('Planned Code Control Flow',`<div class="code-path"><span>VIEW SOURCE</span><b>→</b><span>PROPOSE PATCH</span><b>→</b><span>REVIEW DIFF</span><b>→</b><span>RUN TESTS</span><b>→</b><span>QUALIFY</span><b>→</b><span>COMMIT / BRANCH</span><b>→</b><span>PR / PROMOTE</span></div>`)}${panel('Current Authority',`<div class="control-grid">${cmd?controlCard(cmd):''}</div><div class="info-banner">Direct editing of production Python from the browser is intentionally absent. The future surface will operate Git provenance, not bypass it.</div>`)}</div>`}
function benjaminPage(){return `<div class="page-stack fade-in"><section class="hero"><div class="hero-grid"><div><div class="hero-kicker">ZLJ → BENJAMIN</div><h2>ZLJ's product is governed intelligence, not a trade.</h2><p>The first nine layers exist so Benjamin does not have to reason directly over raw feeds, opaque model outputs, or unqualified claims. Z10 will publish the coherent intelligence object across this boundary.</p></div><aside class="hero-aside"><div class="hero-stat"><span>Z10 publication</span>${badge('UNAVAILABLE')}</div><div class="hero-stat"><span>ZLJ capital authority</span><strong>NONE</strong></div><div class="hero-stat"><span>Execution</span><strong class="locked-text">HAND ONLY</strong></div></aside></div></section>${panel('Benefit Chain',`<div class="truth-list">${(ui.snapshot?.stages||[]).map(s=>truthItem(s.id,`${s.id} ${s.name}`,s.benefit)).join('')}</div>`)}${panel('Future Z10 Contract',`<div class="future-card"><div class="stage-id">Z10</div><div><h3>ZLJ.INTELLIGENCE</h3><p>Will package forecast distribution, context, uncertainty, model/competence lineage, evidence refs, validity/expiry, invalidation conditions, and qualification state into the single product Benjamin consumes.</p></div>${badge('NOT_CONSTRUCTED','muted')}</div>`)}</div>`}
function intelligencePage(){return `<div class="page-stack fade-in"><section class="hero"><div><div class="hero-kicker">NEXT CONSTRUCTION LAYER</div><h2>Z10 — Intelligence Publication</h2><p>This page is deliberately present before Z10 exists so the operator architecture has a stable destination. It remains unavailable until the backend contract is built, tested, qualified, and frozen.</p></div></section>${panel('Current state',`<div class="future-card"><div class="stage-id">Z10</div><div><h3>No intelligence publication authority exists yet.</h3><p>Z1–Z9 may be inspected here, but the console will not fabricate a Benjamin-ready intelligence object.</p></div>${badge('UNAVAILABLE')}</div>`)}</div>`}
function render(){const view=$('#view');if(!ui.snapshot){view.innerHTML='<div class="loading-state"><div class="orbital-loader"><span></span><span></span><span></span></div><p>Resolving durable ZLJ state…</p></div>';return}let html='',title='Overview';if(ui.page==='overview')html=overview();else if(ui.page==='stage'){const s=getStage(ui.stageId);html=stagePage(s);title=`${ui.stageId} · ${s?.name||'Stage'}`}else if(ui.page==='controls'){html=controlsPage();title='Control Center'}else if(ui.page==='certification'){html=certificationPage();title='Certification'}else if(ui.page==='lineage'){html=lineagePage();title='Evidence & Lineage'}else if(ui.page==='development'){html=developmentPage();title='Development'}else if(ui.page==='benjamin'){html=benjaminPage();title='Benjamin Bridge'}else if(ui.page==='intelligence'){html=intelligencePage();title='Z10 Intelligence'}view.innerHTML=html;$('#page-title').textContent=title;bindDynamic();updateChrome()}
function updateChrome(){const s=ui.snapshot?.system||{};$('#side-health').textContent=`Operator journal ${titleCase(s.operator_journal||'unknown')}`;$('#side-dot').className=`status-dot ${s.operator_journal==='VALID'?'cyan':'critical'}`;$('#contract-version').textContent=`Console contract ${ui.snapshot?.contract?.schema_version||'—'}`}
function bindDynamic(){document.querySelectorAll('[data-stage]').forEach(n=>n.addEventListener('click',()=>openView(`stage:${n.dataset.stage}`)));document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>openCommand(b.dataset.command)))}
function openCommand(id){const c=(ui.catalog?.commands||[]).find(x=>x.command_id===id);if(!c)return;ui.command=c;$('#command-modal-title').textContent=c.label;$('#command-modal-description').textContent=c.description;$('#command-result').classList.add('hidden');$('#command-result').textContent='';$('#command-parameters').innerHTML=(c.parameters||[]).map(p=>`<label class="field"><span>${esc(titleCase(p))}</span><input name="${esc(p)}" ${p.endsWith('_ns')?'inputmode="numeric"':''} required /></label>`).join('')||'<div class="info-banner">This command has no parameters.</div>';$('#confirm-row').classList.toggle('hidden',!c.confirmation_required);$('#command-confirm').checked=false;$('#command-submit').disabled=false;$('#command-submit').textContent='Execute';$('#command-modal').classList.remove('hidden')}
function closeModal(){$('#command-modal').classList.add('hidden');ui.command=null}
async function submitCommand(event){event.preventDefault();if(!ui.command)return;const form=new FormData(event.target),params={};for(const name of ui.command.parameters||[]){const raw=form.get(name);params[name]=name.endsWith('_ns')?Number(raw):raw}const requestId=(globalThis.crypto&&crypto.randomUUID)?crypto.randomUUID():`REQ-${Date.now()}-${Math.random().toString(16).slice(2)}`,request={request_id:requestId,command_id:ui.command.command_id,parameters:params,confirm:ui.command.confirmation_required?$('#command-confirm').checked:true};$('#command-submit').disabled=true;$('#command-submit').textContent='Executing…';try{const response=await fetch('/api/control/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)}),payload=await response.json().catch(()=>({status:'error',error:`HTTP ${response.status}`}));$('#command-result').classList.remove('hidden');$('#command-result').textContent=JSON.stringify(payload,null,2);if(response.ok&&payload.status==='ok')await refresh()}catch(error){$('#command-result').classList.remove('hidden');$('#command-result').textContent=String(error)}finally{$('#command-submit').disabled=false;$('#command-submit').textContent='Execute'}}
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
async function refresh(){const[s,c]=await Promise.all([getJSON('/api/operator'),getJSON('/api/control/catalog')]);ui.snapshot=s;ui.catalog=c;renderNav();render()}
function connectEvents(){if(ui.eventSource)ui.eventSource.close();const source=new EventSource('/api/events');ui.eventSource=source;source.addEventListener('snapshot',event=>{try{const next=JSON.parse(event.data);if(next.status==='contract_error')return;ui.snapshot=next;render()}catch(error){console.error(error)}})}
async function boot(){renderNav();try{await refresh();connectEvents()}catch(error){$('#view').innerHTML=`<div class="empty-state"><strong>Operator snapshot unavailable.</strong><p>${esc(error.message)}</p></div>`}$('#refresh-button').addEventListener('click',()=>refresh().catch(console.error));$('#modal-close').addEventListener('click',closeModal);$('#modal-cancel').addEventListener('click',closeModal);$('#command-form').addEventListener('submit',submitCommand);$('#command-modal').addEventListener('click',event=>{if(event.target.id==='command-modal')closeModal()})}
boot();
