(()=>{
'use strict';
let snapshot=null;
let expertActive=false;
let queued=false;
const $=(s)=>document.querySelector(s);
const esc=(v)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nice=(v)=>String(v??'unknown').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const badge=(v)=>{const s=String(v??'');const u=s.toUpperCase();const t=/BUILT|AVAILABLE|VALID|QUALIFIED|PRESENT/.test(u)&&!u.includes('NOT_')?'good':/CANDIDATE|NOT_YET|NO_RUNTIME|BLOCK|DEFER|CURRICULUM_ONLY/.test(u)?'warn':'muted';return `<span class="lab-badge ${t}">${esc(nice(s))}</span>`;};
function intel(){return snapshot?.expert_intelligence||{};}
function ensureNav(){const nav=$('#nav');if(!nav||nav.querySelector('[data-expert-school]'))return;const b=document.createElement('button');b.className='nav-item';b.dataset.expertSchool='true';b.innerHTML='<span class="nav-icon">◇</span><span>Expert School</span>';const registry=nav.querySelector('[data-resolver-registry]');if(registry?.nextSibling)nav.insertBefore(b,registry.nextSibling);else nav.appendChild(b);b.onclick=(e)=>{e.preventDefault();e.stopPropagation();expertActive=true;nav.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();};}
function phaseRows(construction){const labels=[['expert_contracts','Phase 9 · Expert Contracts'],['expert_curriculum','Phase 10 · Expert Curriculum'],['operational_prediction_adapter','Operational prediction bridge'],['question_specific_evaluation','Phase 11 · Question-specific Evaluation'],['competence_memory','Phase 12 · Competence Memory'],['contextual_competence','Phase 13 · Contextual Competence'],['adaptive_expert_assembly','Phase 14 · Adaptive Expert Assembly'],['intelligence_publication','Phase 15 · Intelligence Publication'],['benjamin_publication_gate','Benjamin publication gate']];return labels.map(([key,label])=>`<article><span>${esc(label)}</span>${badge(construction?.[key]||'NOT_BUILT')}</article>`).join('');}
function speciesRows(species){return Object.entries(species||{}).sort((a,b)=>a[0].localeCompare(b[0])).map(([name,count])=>`<div><span>${esc(nice(name))}</span><b>${esc(count)}</b></div>`).join('')||'<div class="lab-empty">No candidate expert contracts.</div>';}
function implementedRows(values){return Object.entries(values||{}).sort((a,b)=>a[0].localeCompare(b[0])).map(([name,count])=>`<div><span>${esc(name)}</span><b>${esc(count)}</b></div>`).join('')||'<div class="lab-empty">No executable expert roles are currently bound.</div>';}
function render(){ensureNav();const view=$('#view');if(!view)return;const title=$('#page-title');if(title)title.textContent='Expert School';document.querySelectorAll('#nav .nav-item').forEach(item=>item.classList.toggle('active',item.hasAttribute('data-expert-school')));const x=intel();if(!x.school){view.innerHTML='<div class="loading-state"><p>Resolving Expert School state…</p></div>';return;}const s=x.school||{},r=x.runtime||{},q=x.qualification||{},b=r.benjamin||{},latest=r.latest_publication,handoff=b.latest_handoff;view.innerHTML=`<div class="lab-stack expert-owner-view" data-expert-view="true">
<section class="lab-stage-hero"><div class="lab-orb">◇</div><div><span class="lab-kicker">ZLJ / LEARNING POPULATION</span><h2>Expert School</h2><p>Curriculum says what mathematical specialists ZLJ intends to study. Implemented experts are the subset with executable model code today. Neither becomes competent until resolver-scored evidence earns it.</p></div>${badge(s.lifecycle_state)}</section>
<section class="expert-status-grid"><article><span>Curriculum experts</span><strong>${esc(s.curriculum_expert_count||0)}</strong><small>planned question-bound specialist roles</small></article><article><span>Implemented experts</span><strong>${esc(s.implemented_expert_count||0)}</strong><small>executable prediction-to-claim roles</small></article><article><span>Scored outcomes</span><strong>${esc(r.score_count||0)}</strong><small>resolver-graded observations</small></article><article><span>Internal intelligence</span><strong>${esc(r.publication_count||0)}</strong><small>${r.internal_intelligence_exists?'exists':'does not exist'}; not Benjamin-consumable</small></article></section>
<section class="lab-panel"><header><div><span class="lab-kicker">CONSTRUCTION</span><h3>Intelligence lifecycle</h3></div>${badge(r.journal)}</header><div class="expert-phase-list">${phaseRows(x.construction)}</div></section>
<section class="expert-two-col"><section class="lab-panel"><header><div><span class="lab-kicker">CURRICULUM SPECIES</span><h3>Mathematical diversity</h3></div><small>Planned study population, not claimed implementation</small></header><div class="expert-species">${speciesRows(s.species_counts)}</div></section><section class="lab-panel"><header><div><span class="lab-kicker">IMPLEMENTED INVENTORY</span><h3>Executable expert roles</h3></div><small>Real model code bound to exact exams</small></header><div class="expert-species">${implementedRows(s.implemented_by_question)}</div></section></section>
<section class="lab-panel"><header><div><span class="lab-kicker">EARNED STATE</span><h3>Qualification boundary</h3></div></header><div class="expert-boundary"><div><span>Population</span>${badge(q.expert_population)}</div><div><span>Competence</span>${badge(q.earned_competence)}</div><div><span>Internal intelligence</span>${badge(q.internal_intelligence)}</div><div><span>Benjamin eligibility</span>${badge(b.eligibility_status||q.benjamin_eligibility)}</div><div><span>Benjamin handoff</span>${badge(q.benjamin_handoff)}</div><div><span>Capital authority</span><strong>NONE</strong></div></div></section>
<section class="lab-panel"><header><div><span class="lab-kicker">ADAPTIVE REASONING</span><h3>How ZLJ reasons on model testimony</h3></div></header><div class="expert-flow"><span>Question-bound prediction</span><i>→</i><span>Expert claim</span><i>→</i><span>Resolver outcome</span><i>→</i><span>Competence memory</span><i>→</i><span>Current context</span><i>→</i><span>Adaptive weights</span><i>→</i><span>ZLJ intelligence</span></div><p class="expert-note">Evidence overlap is penalized so correlated models do not masquerade as independent witnesses. Experts with little history shrink toward neutral trust until they earn stronger contextual competence.</p></section>
<section class="lab-panel"><header><div><span class="lab-kicker">BENJAMIN PUBLICATION GATE</span><h3>${handoff?'Qualified handoff published':(latest?'Internal intelligence is not a Benjamin handoff':'No runtime intelligence published yet')}</h3></div>${badge(b.eligibility_status||'NONE')}</header>${latest?`<div class="expert-publication"><div><span>Internal publication</span><strong>${esc(r.internal_intelligence_exists?'EXISTS':'DOES_NOT_EXIST')}</strong></div><div><span>Eligibility</span><strong>${esc(b.eligibility_status||'NONE')}</strong></div><div><span>Blocking reasons</span><code>${esc((b.blocking_reasons||[]).join(', ')||'none')}</code></div><div><span>Policy version</span><code>${esc(b.policy_version||'none')}</code></div><div><span>Qualification timestamp</span><code>${esc(b.qualification_timestamp_ns??'none')}</code></div><div><span>Handoff count</span><strong>${esc(b.handoff_count||0)}</strong></div></div>`:'<p>The publication machinery is built, but ZLJ will not manufacture intelligence. An internal publication appears only after executable experts make real claims that are resolved, scored, assembled, and published. Benjamin may consume it only after this gate.</p>'}<div class="lab-boundary"><span>ZLJ perception</span><strong>YES</strong><span>Benjamin economic decision</span><strong>NO</strong><span>Watchman authorization</span><strong>NO</strong><span>Hand execution</span><strong>NO</strong></div></section></div>`;}
function decorate(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;ensureNav();if(expertActive&&!$('#view [data-expert-view]'))render();});}
document.addEventListener('click',(e)=>{if(e.target.closest?.('#nav [data-page], #nav [data-resolver-registry]'))expertActive=false;},true);new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});function accept(v){if(v?.contract?.name!=='zlj-operator-console')return;snapshot=v;if(expertActive)render();else decorate();}(async()=>{try{const r=await fetch('/api/operator',{cache:'no-store'});if(r.ok)accept(await r.json());}catch(_){}})();window.addEventListener('zlj-operator-snapshot',(event)=>accept(event.detail));decorate();
})();