const state={snapshot:null,catalog:null,page:'overview'};
const $=(s)=>document.querySelector(s);
const esc=(v)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nice=(v)=>String(v??'unknown').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const fmt=(v)=>typeof v==='number'?new Intl.NumberFormat('en-US',{maximumFractionDigits:3}).format(v):String(v??'—');
const statusTone=(v)=>{const s=String(v??'').toUpperCase();if(/CERT|VALID|SUPPORTED|AVAILABLE/.test(s)&&!s.includes('UNAVAILABLE'))return'good';if(/BLOCK|DEGRADED|WARN/.test(s))return'warn';if(/NOT_EARNED|INVALID|ERROR|LOCKED/.test(s))return'bad';return'muted'};
const badge=(v)=>`<span class="lab-badge ${statusTone(v)}">${esc(nice(v))}</span>`;
const stageMap={
 Z1:{name:'Market Feed',icon:'◉',question:'What market evidence is arriving, from where, and can it be trusted?',benefit:'Traceable source facts before any reasoning begins.'},
 Z2:{name:'Market State',icon:'◇',question:'What did each instrument and venue look like at a specific point in time?',benefit:'A point-in-time state instead of raw packet chaos.'},
 Z3:{name:'Forecasts',icon:'↗',question:'What falsifiable claims are the models making?',benefit:'Forecasts that can later be proven right, wrong, or unresolved.'},
 Z4:{name:'Model Lab',icon:'⬡',question:'Which forecasting hypotheses exist and what are they designed to predict?',benefit:'A diverse model inventory rather than one opaque oracle.'},
 Z5:{name:'Model Authority',icon:'⟳',question:'Which models have actually earned permission to influence serving intelligence?',benefit:'Lifecycle evidence separates candidates from qualified contributors.'},
 Z6:{name:'Outcomes',icon:'⊙',question:'What actually happened after each forecast?',benefit:'Reality is resolved with a fixed policy instead of hindsight.'},
 Z7:{name:'Competence',icon:'◈',question:'Where is each model strong, weak, calibrated, biased, or evidence-starved?',benefit:'Trust is measured rather than assigned by reputation.'},
 Z8:{name:'Belief Assembly',icon:'✣',question:'How is ZLJ combining specialist forecasts into one auditable belief?',benefit:'Adaptive belief with bounded, evidence-driven weighting.'},
 Z9:{name:'Market Context',icon:'◎',question:'What broader liquidity, volatility, correlation and derivative structure surrounds the instrument?',benefit:'Situational awareness instead of context-blind forecasts.'}
};
const nav=[
 ['overview','Overview','⌂'],['live','Live Market','⌁'],['feed','Market Feed','◉'],['state','Market State','◇'],['forecasts','Forecasts','↗'],['models','Model Lab','⬡'],['outcomes','Outcomes','⊙'],['competence','Competence','◈'],['assembly','Belief Assembly','✣'],['context','Market Context','◎'],['experiments','Experiments','⚗'],['certification','Certification','✓'],['evidence','Evidence & Lineage','⌘'],['controls','Control Center','⚙'],['benjamin','Benjamin Output','B']
];
const stageForPage={feed:'Z1',state:'Z2',forecasts:'Z3',models:'Z4',outcomes:'Z6',competence:'Z7',assembly:'Z8',context:'Z9'};
function stage(id){return(state.snapshot?.stages||[]).find(s=>s.id===id)||{};}
function metricCards(metrics={}){const entries=Object.entries(metrics).filter(([,v])=>typeof v!=='object').slice(0,6);if(!entries.length)return'<div class="lab-empty">No durable runtime records yet.</div>';return `<div class="lab-metrics">${entries.map(([k,v])=>`<article><span>${esc(nice(k))}</span><strong>${esc(fmt(v))}</strong></article>`).join('')}</div>`;}
function renderNav(){const navEl=$('#nav');navEl.innerHTML=`<div class="lab-nav-title">INTELLIGENCE LAB</div>${nav.map(([key,label,icon])=>`<button class="nav-item ${state.page===key?'active':''}" data-page="${key}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}<div class="lab-nav-rule"></div><div class="lab-nav-caption">PERCEPTION ONLY<br><b>Capital authority: NONE</b></div>`;navEl.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render();});}
function productFlow(){const ids=['Z1','Z2','Z3','Z4','Z5','Z6','Z7','Z8','Z9'];return `<div class="lab-flow">${ids.map((id,i)=>{const m=stageMap[id],s=stage(id);return `<div class="lab-flow-node ${statusTone(s.availability)}"><i>${m.icon}</i><b>${m.name}</b><small>${esc(nice(s.availability||'unknown'))}</small></div>${i<ids.length-1?'<span class="lab-arrow">→</span>':''}`}).join('')}<span class="lab-arrow">→</span><div class="lab-flow-node future"><i>✦</i><b>Intelligence</b><small>for Benjamin</small></div></div>`;}
function overview(){const feed=stage('Z1'),rep=stage('Z2'),pred=stage('Z3'),ctx=stage('Z9'),cert=state.snapshot?.certification||{};return `<div class="lab-stack"><section class="lab-hero"><div><div class="lab-kicker">EPINNOX / ZLJ · INTELLIGENCE LABORATORY + PERCEPTION CONSOLE</div><h2>See the market. Measure what was known. Build belief that can defend itself.</h2><p>ZLJ turns noisy market evidence into structured perception, falsifiable forecasts, measured model competence, adaptive belief, and broader market context. Its finished product is intelligence for Benjamin—not a trade and not capital authority.</p><div class="lab-principle"><span>MARKET</span><b>→</b><span>PERCEPTION</span><b>→</b><span>FORECAST</span><b>→</b><span>MEASURE</span><b>→</b><span>ASSEMBLE</span><b>→</b><span>CONTEXT</span><b>→</b><span>BENJAMIN</span></div></div><aside><div><span>Operating mode</span><strong>SHADOW ONLY</strong></div><div><span>Live execution</span><strong class="danger">LOCKED</strong></div><div><span>Capital authority</span><strong>NONE</strong></div><div><span>Intelligence publication</span><strong>NOT BUILT YET</strong></div></aside></section>
<section class="lab-summary-grid"><article><span>Canonical market batches</span><strong>${esc(fmt(feed.metrics?.canonical_batches||0))}</strong><small>provider evidence retained</small></article><article><span>Market-state frames</span><strong>${esc(fmt(rep.metrics?.representation_frames||0))}</strong><small>point-in-time representations</small></article><article><span>Durable forecasts</span><strong>${esc(fmt(pred.metrics?.prediction_entries||0))}</strong><small>falsifiable claims</small></article><article><span>Context frames</span><strong>${esc(fmt(ctx.metrics?.context_frames||0))}</strong><small>market-wide situational state</small></article></section>
<section class="lab-panel"><header><div><span class="lab-kicker">SYSTEM MAP</span><h3>How perception becomes intelligence</h3></div><small>Every node is inspectable and evidence-bound.</small></header>${productFlow()}</section>
<section class="lab-grid-2"><article class="lab-panel"><header><div><span class="lab-kicker">DATA QUALITY</span><h3>Truth before inference</h3></div></header><div class="lab-truth"><div><i>⏱</i><b>Freshness</b><span>Stale evidence must identify itself.</span></div><div><i>⌘</i><b>Provenance</b><span>Inputs bind exact source identities and hashes.</span></div><div><i>◇</i><b>Point-in-time safety</b><span>Future-known evidence cannot leak backward.</span></div><div><i>↺</i><b>Replayability</b><span>Frozen evidence must reproduce later.</span></div><div><i>∅</i><b>Unknown stays unknown</b><span>Unavailable context is not silently treated as neutral.</span></div></div></article><article class="lab-panel"><header><div><span class="lab-kicker">CURRENT EPISTEMIC STATE</span><h3>What ZLJ has actually earned</h3></div></header><div class="lab-cert-mini"><div><span>Historical adaptive performance</span>${badge(cert.z8_historical?.decision||'NOT_EARNED')}</div><div><span>Prospective mechanism</span>${badge(cert.z8_prospective?.decision||'UNAVAILABLE')}</div><div><span>Market-context construction</span>${badge(cert.z9?.construction||'UNAVAILABLE')}</div><div><span>Market-wide empirical support</span>${badge(cert.z9?.market_wide_empirical||'DATA_BLOCKED')}</div></div></article></section></div>`;}
function stagePage(id){const s=stage(id),m=stageMap[id];return `<div class="lab-stack"><section class="lab-stage-hero"><div class="lab-orb">${m.icon}</div><div><span class="lab-kicker">PERCEPTION WORKBENCH</span><h2>${m.name}</h2><p>${m.question}</p></div>${badge(s.availability||'unknown')}</section><section class="lab-grid-2"><article class="lab-panel"><header><div><span class="lab-kicker">DURABLE STATE</span><h3>What exists right now</h3></div></header>${metricCards(s.metrics||{})}<pre class="lab-json">${esc(JSON.stringify(s.metrics||{},null,2))}</pre></article><article class="lab-panel"><header><div><span class="lab-kicker">BENJAMIN BENEFIT</span><h3>Why this matters downstream</h3></div></header><div class="lab-benefit"><b>${m.benefit}</b><p>${esc(s.benefit||'')}</p></div><div class="lab-boundary"><span>ZLJ authority</span><strong>PERCEPTION / INTELLIGENCE ONLY</strong><span>Economic decision</span><strong>BELONGS TO BENJAMIN</strong></div></article></section><section class="lab-panel"><header><div><span class="lab-kicker">LINEAGE POSITION</span><h3>Where this fits in the evidence chain</h3></div></header>${productFlow()}</section></div>`;}
function live(){return `<div class="lab-stack"><section class="lab-stage-hero"><div class="lab-orb">⌁</div><div><span class="lab-kicker">LIVE MARKET</span><h2>What ZLJ is seeing now</h2><p>This surface will become the real-time market observatory: feed quality, spreads, liquidity, volatility, cross-venue state, correlations and current context. Only durable values already exposed by the kernel are shown today.</p></div>${badge('CONSTRUCTED')}</section><section class="lab-grid-3"><article class="lab-panel"><h3>Feed health</h3>${metricCards(stage('Z1').metrics||{})}</article><article class="lab-panel"><h3>Market-state production</h3>${metricCards(stage('Z2').metrics||{})}</article><article class="lab-panel"><h3>Context production</h3>${metricCards(stage('Z9').metrics||{})}</article></section><section class="lab-panel lab-placeholder"><span class="lab-kicker">FRONTEND CONTRACT</span><h3>Live visual field</h3><p>Reserved for real instrument tiles, microstructure heatmaps, venue comparison, breadth, correlation topology, basis curves and regime transitions. This page intentionally refuses synthetic live prices.</p></section></div>`;}
function experiments(){const mon=state.snapshot?.monitor?.sections||{};const active=mon.active_experiment?.data||{};const hist=mon.experiment_history?.data||{};return `<div class="lab-stack"><section class="lab-stage-hero"><div class="lab-orb">⚗</div><div><span class="lab-kicker">RESEARCH</span><h2>Experiments</h2><p>Preregister, observe, falsify and freeze. Research results remain separate from serving authority until qualification is earned.</p></div></section><section class="lab-grid-2"><article class="lab-panel"><h3>Active experiment</h3><pre class="lab-json">${esc(JSON.stringify(active,null,2))}</pre></article><article class="lab-panel"><h3>Experiment history</h3><pre class="lab-json">${esc(JSON.stringify(hist,null,2))}</pre></article></section></div>`;}
function certification(){const c=state.snapshot?.certification||{};return `<div class="lab-stack"><section class="lab-stage-hero"><div class="lab-orb">✓</div><div><span class="lab-kicker">CLAIM CONTROL</span><h2>Certification</h2><p>The console should make it difficult to confuse “the mechanism works” with “the mechanism has demonstrated economic edge.”</p></div></section><section class="lab-cert-grid"><article><span>Adaptive historical experiment</span><strong>${esc(c.z8_historical?.experiment_id||'—')}</strong>${badge(c.z8_historical?.decision||'NOT_EARNED')}<p>Frozen evidence remains a first-class result, including failure.</p></article><article><span>Prospective mechanism</span><strong>${esc(c.z8_prospective?.experiment_id||'—')}</strong>${badge(c.z8_prospective?.decision||'UNAVAILABLE')}<p>Prospective operation is not automatically a profitability claim.</p></article><article><span>Market context</span><strong>Construction</strong>${badge(c.z9?.construction||'UNAVAILABLE')}<p>Context mechanics may be certified while empirical superiority stays blocked.</p></article></section></div>`;}
function evidence(){return `<div class="lab-stack"><section class="lab-stage-hero"><div class="lab-orb">⌘</div><div><span class="lab-kicker">EVIDENCE</span><h2>Lineage Explorer</h2><p>Start from any future intelligence object and walk backward through belief, competence, outcomes, forecasts, market state and source observations.</p></div></section><section class="lab-panel"><div class="lab-evidence-chain"><div><b>Market evidence</b><small>provider facts</small></div><span>→</span><div><b>Market state</b><small>point-in-time</small></div><span>→</span><div><b>Forecast</b><small>falsifiable claim</small></div><span>→</span><div><b>Outcome</b><small>resolved truth</small></div><span>→</span><div><b>Competence</b><small>measured trust</small></div><span>→</span><div><b>Belief</b><small>assembled view</small></div><span>→</span><div><b>Context</b><small>situational overlay</small></div><span>→</span><div class="future"><b>Intelligence</b><small>Benjamin input</small></div></div></section></div>`;}
function controls(){const commands=state.catalog?.commands||state.snapshot?.controls?.commands||[];return `<div class="lab-stack"><section class="lab-stage-hero"><div class="lab-orb">⚙</div><div><span class="lab-kicker">OPERATOR CONTROL</span><h2>Control Center</h2><p>The browser may request operations; domain contracts remain authoritative. Controls with no governed backend stay unavailable.</p></div></section><section class="lab-control-grid">${commands.map(c=>`<article class="lab-control ${String(c.state).toLowerCase()}"><div><span>${esc(c.domain)}</span><h3>${esc(c.label)}</h3><p>${esc(c.description)}</p></div>${badge(c.state)}<small>${esc(c.control_class)} · ${esc(c.required_scope||'authority contract pending')}</small></article>`).join('')}</section></div>`;}
function benjamin(){return `<div class="lab-stack"><section class="lab-stage-hero"><div class="lab-orb">B</div><div><span class="lab-kicker">INSTITUTIONAL OUTPUT</span><h2>Benjamin Output</h2><p>This is the handoff boundary. ZLJ should publish coherent intelligence—not expose Benjamin to raw model chaos.</p></div>${badge('NOT_CONSTRUCTED')}</section><section class="lab-grid-2"><article class="lab-panel"><h3>Future intelligence object</h3><div class="lab-object"><span>Instrument / horizon</span><span>Proposition</span><span>Probability + expected move</span><span>Uncertainty</span><span>Market context</span><span>Model agreement</span><span>Supporting + contradictory evidence</span><span>Invalidation</span><span>Known at / valid until</span><span>Exact lineage</span></div></article><article class="lab-panel"><h3>Authority boundary</h3><div class="lab-boundary"><span>ZLJ may</span><strong>OBSERVE · FORECAST · CALIBRATE · PUBLISH INTELLIGENCE</strong><span>ZLJ may not</span><strong class="danger">ALLOCATE CAPITAL · AUTHORIZE RISK · EXECUTE ORDERS</strong><span>Next authority</span><strong>BENJAMIN</strong></div></article></section></div>`;}
function render(){renderNav();const title=nav.find(n=>n[0]===state.page)?.[1]||'Overview';$('#page-title').textContent=title;let html='';if(state.page==='overview')html=overview();else if(state.page==='live')html=live();else if(stageForPage[state.page])html=stagePage(stageForPage[state.page]);else if(state.page==='experiments')html=experiments();else if(state.page==='certification')html=certification();else if(state.page==='evidence')html=evidence();else if(state.page==='controls')html=controls();else html=benjamin();$('#view').innerHTML=html;}
async function load(){try{const [snapshot,catalog]=await Promise.all([fetch('/api/operator').then(r=>r.json()),fetch('/api/control/catalog').then(r=>r.json())]);state.snapshot=snapshot;state.catalog=catalog;$('#side-health').textContent='Durable state resolved';$('#side-dot').className='status-dot cyan';$('#contract-version').textContent=`Contract ${snapshot.contract?.schema_version||'—'}`;render();}catch(err){$('#view').innerHTML=`<div class="lab-empty"><b>Unable to resolve ZLJ state.</b><pre>${esc(err)}</pre></div>`;$('#side-health').textContent='State unavailable';}}
$('#refresh-button').onclick=load;
load();